# Generated by Django 4.2.6 on 2024-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumbusholachanjo',
            name='KundiLaKukuWake',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kundi La Kuku Wake'),
        ),
        migrations.AlterField(
            model_name='kumbusholachanjo',
            name='UmriWaKukuKwaSiku',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umri Wa Kuku Kwa Siku'),
        ),
        migrations.AlterField(
            model_name='kumbusholachanjo',
            name='UmriWaKukuKwaWiki',
            field=models.IntegerField(blank=True, null=True, verbose_name='Umri Wa Kuku Kwa Wiki'),
        ),
    ]
