# Generated by Django 4.2.6 on 2024-10-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_ainazakuku_totalmepercentagerequired_finisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyakulaorder',
            name='TotalMEPercentageRequired',
            field=models.CharField(blank=True, default=0, max_length=300, null=True, verbose_name='Jumla Ya  Kiasi Cha ME Kwenye Chakula - Kg/kca'),
        ),
    ]
