# Generated by Django 4.2.6 on 2024-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_vyakulaorder_totalmepercentagerequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='phone'),
        ),
    ]
