# Generated by Django 4.2.6 on 2024-10-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_myuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WazalishajiWaHuduma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Simu Ya Mzalishaji')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina La Mzalishaji')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yake')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kampuni/Jina La Biashara Yake')),
                ('Maelezo', models.TextField(blank=True, max_length=10000, null=True)),
                ('Wilaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Mzalishaji')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App.mikoa', verbose_name='Mkoa')),
            ],
            options={
                'verbose_name_plural': 'Wazalishaji Wa Huduma',
            },
        ),
        migrations.CreateModel(
            name='WatejaWote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaMteja', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jina La Mteja')),
                ('phoneYaMteja', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Ya Simu Ya Mteja')),
                ('emailYaMteja', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('WilayaYaMteja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya')),
                ('PichaYaMteja', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Mteja')),
                ('is_checked', models.BooleanField(blank=True, default=False, null=True)),
                ('PaidAmount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Alicholipa')),
                ('RemainedAmount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Anachodaiwa')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Simu Ya Mzalishaji')),
                ('Mzalishaji', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina La Mzalishaji')),
                ('JinaLaHuduma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Huduma Anayohitaji')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yake')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kampuni/Jina La Biashara Yake')),
                ('Maelezo', models.TextField(blank=True, max_length=10000, null=True)),
                ('Mkoa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mkoa')),
                ('Wilaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Mzalishaji')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('MkoaWaMteja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App.mikoa', verbose_name='Mkoa')),
            ],
            options={
                'verbose_name_plural': 'Wanunuzi',
            },
        ),
        migrations.CreateModel(
            name='HudumazaWazalishaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaHuduma', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina La Huduma')),
                ('Maelezo', models.TextField(blank=True, max_length=10000, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, default=0, null=True, verbose_name='Bei Ya Jumla Ya Bidhaa')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Mzalishaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App.wazalishajiwahuduma', verbose_name='Jina La Mtoa Huduma')),
            ],
            options={
                'verbose_name_plural': 'Wazalishaji Wa Huduma',
            },
        ),
    ]
