# Generated by Django 4.2.6 on 2024-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_wazalishajiwahuduma_watejawote_hudumazawazalishaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='hudumazawazalishaji',
            name='PichaYaHuduma',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Huduma'),
        ),
    ]
