# Generated by Django 4.2.6 on 2024-10-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_hudumazawazalishaji_pichayahuduma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hudumazawazalishaji',
            options={'verbose_name_plural': 'Huduma Za Wazalishaji'},
        ),
        migrations.AlterModelOptions(
            name='watejawote',
            options={'verbose_name_plural': 'Wateja'},
        ),
        migrations.AddField(
            model_name='watejawote',
            name='SikuYaKupokea',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Siku Ya Kupokea Bidhaa'),
        ),
    ]
