# Generated by Django 4.2.6 on 2024-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_watejawote_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='watejawote',
            name='day_is_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watejawote',
            name='message_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
